version: '3.5'  

services: 
    backend:
      build: ./ml-kurkkumopo-backend
      ports: 
        - 5000:5000 
      depends_on:
        - training
      volumes:
        - model:/src/model

    frontend:
      build: ./ml-kurkkumopo-frontend
      ports: 
        - 3000:3000 

    training:
      build: ./ml-kurkkumopo-training
      container_name: training
      volumes:
        - imgs:/src/imgs
        - model:/src/model

volumes:
  model:
  imgs: