version: '3.5'  

services: 
    backend-example-docker:
      build: ../../part1/1_11/
      ports: 
        - 8000:8000 
      environment:
        - FRONT_URL=http://localhost:5000
        - REDIS=redis
        - REDIS_PORT=6379
        - DB_USERNAME=postgres
        - DB_PASSWORD=secret
        - DB_NAME=postgres
        - DB_HOST=db
      container_name: backend-example-docker

    frontend-example-docker:
      build: ../../part1/1_10/
      ports: 
        - 5000:5000
      container_name: frontend-example-docker
      environment:
        - API_URL=http://localhost/api

    redis:
      image: redis
      container_name: redis

    db:
      image: postgres
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: secret
      container_name: db

    nginx:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80