version: '3.5'  

services: 
    backend-example-docker:
      build: ../../part1/1_11/
      ports: 
        - 8000:8000 
      environment:
        - FRONT_URL=http://localhost:5000
        - REDIS=redis
        - REDIS_PORT=6379

    frontend-example-docker:
      build: ../../part1/1_10/
      ports: 
        - 5000:5000 

    redis:
      image: redis
      container_name: redis